apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: vertexchain
spec:
  type: LoadBalancer
  selector:
    app: vertexchain-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
