apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: vertexchain-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: vertexchain-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: vertexchain-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: vertexchain-staging
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: backend-sa
  namespace: vertexchain-prod
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-sa
  namespace: vertexchain-prod
